# Generated by Django 5.2.9 on 2026-05-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_annotation_bookmark_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='target_department',
            field=models.CharField(blank=True, choices=[('sciences', 'Sciences et Technologies'), ('management', 'Management et Gestion'), ('lettres', 'Lettres et Sciences Humaines')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='target_filiere',
            field=models.CharField(blank=True, help_text='Option spécifique (ex: Informatique)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='target_level',
            field=models.CharField(blank=True, choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('DOC', 'Doctorat')], max_length=10, null=True),
        ),
    ]
