# Generated by Django 5.2.9 on 2026-05-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_target_department_book_target_filiere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='target_department',
            field=models.CharField(blank=True, choices=[('brazzaville', 'Brazzaville'), ('pointe_noire', 'Pointe-Noire'), ('ouesso', 'Ouesso')], max_length=50, null=True),
        ),
    ]
