# Generated by Django 5.2.9 on 2026-05-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_target_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='target_campus',
            field=models.CharField(blank=True, choices=[('brazzaville', 'Brazzaville'), ('pointe_noire', 'Pointe-Noire'), ('ouesso', 'Ouesso')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='target_department',
            field=models.CharField(blank=True, choices=[('sciences', 'Sciences et Technologies'), ('management', 'Management et Gestion'), ('lettres', 'Lettres et Sciences Humaines')], max_length=50, null=True),
        ),
    ]
