# Generated by Django 5.2.9 on 2026-05-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_target_campus_alter_book_target_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='target_campus',
            field=models.CharField(blank=True, choices=[('all', 'Tous les campus'), ('brazzaville', 'Brazzaville'), ('pointe_noire', 'Pointe-Noire'), ('ouesso', 'Ouesso')], max_length=50, null=True),
        ),
    ]
