# Generated by Django 5.2.9 on 2026-05-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_target_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Campuses',
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='target_campus',
        ),
        migrations.AddField(
            model_name='book',
            name='target_campuses',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.campus'),
        ),
    ]
