# Generated by Django 5.2.9 on 2026-05-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_campus_remove_book_target_campus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
