# Generated by Django 5.2.9 on 2026-05-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Coup de cœur (Trésor du Mois)'),
        ),
    ]
