# Generated by Django 5.2.9 on 2026-05-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Représentation vectorielle pour la recherche sémantique', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Texte extrait du PDF pour analyse'),
        ),
    ]
