# Generated by Django 5.2.9 on 2026-05-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('sciences', 'Sciences et Technologies'), ('management', 'Management et Gestion'), ('lettres', 'Lettres et Sciences Humaines')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='filiere',
            field=models.CharField(blank=True, help_text='Ex: Informatique, Droit, Marketing', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('DOC', 'Doctorat')], max_length=10, null=True),
        ),
    ]
