# Generated by Django 5.2.9 on 2026-05-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='campus',
            field=models.CharField(blank=True, choices=[('brazzaville', 'Brazzaville'), ('pointe_noire', 'Pointe-Noire'), ('ouesso', 'Ouesso')], max_length=50, null=True),
        ),
    ]
