# Generated by Django 5.2.9 on 2026-05-18 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_campus'),
        ('books', '0010_campus_remove_book_target_campus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.campus'),
        ),
    ]
