# Generated by Django 5.2.9 on 2026-05-22 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la filière')),
                ('department', models.CharField(choices=[('sciences', 'Sciences et Technologies'), ('management', 'Management et Gestion'), ('lettres', 'Lettres et Sciences Humaines')], max_length=50, verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.filiere', verbose_name='Filière'),
        ),
    ]
