# Generated by Django 5.2.9 on 2026-05-24 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_email'),
        ('books', '0012_book_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.campus', verbose_name='Campus'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('DOC', 'Doctorat')], max_length=10, null=True, verbose_name="Niveau d'études"),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Étudiant'), ('teacher', 'Enseignant'), ('librarian', 'Bibliothécaire'), ('admin', 'Administrateur')], default='student', max_length=20),
        ),
    ]
