# Generated by Django 5.2.9 on 2026-05-31 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userpreference'),
        ('books', '0014_book_embedding_book_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='current_book_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book', verbose_name='Livre en cours de coaching'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_coaching_mode',
            field=models.BooleanField(default=False, verbose_name='Mode Coach activé'),
        ),
    ]
